server:
  port: 9000
spring:
  profiles:
    active: local
    include:
      - domain
      - thirdparty
      - swagger
      - cloud
      - aws
  datasource:
    data: classpath:schema/schema-session.sql