server:
  port: 9000
spring:
  session:
    store-type: jdbc
  profiles:
    active: local
    include:
      - domain
      - thirdparty
      - swagger
      - rds
  datasource:
    data: classpath:schema/schema-session.sql