server:
  port: 9000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
    include:
      - domain
      - thirdparty
      - swagger
      - cloud
      - aws
  datasource:
    data: classpath:schema/schema-session.sql